# Generated by Django 3.2 on 2021-04-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplychainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='manufacturer',
            new_name='manufacture',
        ),
    ]
