# Generated by Django 3.2 on 2021-04-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplychainapp', '0005_products_manufacturerid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
