# Generated by Django 3.2 on 2021-04-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychainapp', '0012_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(default=0, upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
