# Generated by Django 3.2 on 2021-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychainapp', '0013_auto_20210430_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
