# Generated by Django 3.2 on 2021-05-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychainapp', '0018_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordertrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('orderid', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('manufacturerid', models.CharField(max_length=100)),
                ('trasactionhash', models.CharField(max_length=100)),
            ],
        ),
    ]
