# Generated by Django 3.2 on 2021-05-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychainapp', '0019_ordertrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertrack',
            name='orderstatus',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
